#version: '3.9'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
      - ./scripts/grafana/dashboards:/etc/grafana/demo-dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./scripts/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=5m'
      - '--storage.tsdb.retention.size=10GB'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  fluentbit:
    image: fluent/fluent-bit:3.1.6
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./scripts/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./logs:/app/logs
  nginx:
    image: nginx
    ports:
      - "8081:80"
    logging:
      driver: fluentd
      options:
        tag: nginx
        fluentd-sub-second-precision: 'true'

  loki:
    image: grafana/loki:3.1.1
    ports:
      - "3100:3100"
    volumes:
      - ./scripts/loki:/etc/loki
    command: -config.file=/etc/loki/config.yaml
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - "9100:9100"

#  backend-app:
#    build: .
#    ports:
#      - "8080:8080"

volumes:
  grafana_data:
  prometheus_data:
